name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
         # if condition to prevent version bumps on pull request -> only on push (i.e. merge) after review of pull request 
         # and commit message doesnt contain #skip
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }} 
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided to third-party action which need the token for authentication in your repository
          DEFAULT_BUMP: patch
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }} # if condition to prevent deployment on pull request -> only on push (i.e. merge) after review of pull request
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-deploy-the-new" 
          heroku_email: "wagner.a.muller@gmail.com"



