name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
         # if condition to prevent version bumps on pull request -> only on push (i.e. merge) after review of pull request 
         # and commit message doesnt contain #skip
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }} 
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided to third-party action which need the token for authentication in your repository
          DEFAULT_BUMP: patch
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }} # if condition to prevent deployment on pull request -> only on push (i.e. merge) after review of pull request
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-deploy-the-new" 
          heroku_email: "wagner.a.muller@gmail.com"
          healthcheck: "https://pokedex-deploy-the-new.herokuapp.com/health"
          checkstring: "1"
          rollbackonhealthcheckfailed: true
      - name: notification on success
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'action-slack',
              attachments: [{
                color: 'good',
                text: `a new version deployed to https://afternoon-bayou-62251.herokuapp.com (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ success() }}
      - name: notification on failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}



